### ISSUE TITLE
Syncing cloud bookmarks with chrome does not handle background deletes

### ISSUE THREAD

**Issue by akshaykumar90** [akshaykumar90/savory#13]
If a bookmark is removed in Chrome when Savory Bookmarks Manager is not open, the bookmark is not deleted from MongoDB. The sync logic does not account for this behavior.

**Comment by curatorman** [comment]
Yes! I would love this feature.

**Comment by akshaykumar90** [comment]
This should be fixed by 74d77647c55d7f38d850915097aef61a50cbc359.
